# Generated by Django 2.0.1 on 2018-01-18 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null='False')),
                ('author', models.CharField(max_length=100, null='False')),
                ('date_publish', models.DateField()),
                ('number_of_page', models.IntegerField()),
            ],
        ),
    ]
