# Generated by Django 2.0.1 on 2018-01-19 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20180119_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateTimeField(verbose_name=['%Y-%m-%d']),
        ),
    ]
