# Generated by Django 2.0.1 on 2018-01-19 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_auto_20180119_0958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateField(verbose_name=['%Y-%m-%d']),
        ),
    ]
