# Generated by Django 2.0.1 on 2018-01-19 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0009_auto_20180119_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
