# Generated by Django 2.0.1 on 2018-01-19 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0010_auto_20180119_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateTimeField(),
        ),
    ]
