# Generated by Django 2.0.1 on 2018-01-19 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0015_auto_20180119_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_page',
            field=models.IntegerField(),
        ),
    ]
