# Generated by Django 2.0.1 on 2018-01-19 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0016_auto_20180119_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='date_publish',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='number_of_page',
            field=models.IntegerField(null=True),
        ),
    ]
