# Generated by Django 2.0.1 on 2018-01-19 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0017_auto_20180119_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_page',
            field=models.IntegerField(default='0'),
        ),
    ]
