# Generated by Django 2.0.1 on 2018-01-19 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0019_auto_20180119_1202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='number_of_page',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
